
###REGISTER USER
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "fullName": "Alex Black",
  "username": "alex",
  "password": "password123",
  "role": "ADMIN"
}



###LOGIN & GET AUTH TOKEN & REFRESH TOKEN
# @name login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "alex",
  "password": "password123"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);

%}

###POST PRODUCT
POST http://localhost:8080/api/products
Authorization: {{access_token}}
Content-Type: application/json

{
  "name": "Product 1",
  "price": "100.00"
}


###GET PRODUCT BY ID
GET http://localhost:8080/api/products/1
Authorization: {{access_token}}
Content-Type: application/json

{}



###POST PRODUCT
POST http://localhost:8080/api/products
Authorization: {{access_token}}
Content-Type: application/json

{
  "name": "Product 2",
  "price": "200.00"
}


###UPDATE PRODUCT
PUT http://localhost:8080/api/products/1
Authorization: {{access_token}}
Content-Type: application/json

{
  "name": "Product 1 Updated",
  "price": "150.00"
}

###UPDATE PRODUCT
PUT http://localhost:8080/api/products/2
Authorization: {{access_token}}
Content-Type: application/json

{
  "name": "Product 2 Updated",
  "price": "250.00"
}


###GET ALL PRODUCTS
GET http://localhost:8080/api/products
Authorization: {{access_token}}
Content-Type: application/json

{}

###DELETE PRODUCT
DELETE http://localhost:8080/api/products/1
Authorization: {{access_token}}
Content-Type: application/json
